language: php

php:
  - 7.2
  - 7.3

env:
  - FILE_OWNER=2000
  - FILE_GROUP=2000

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
